# Generated by Django 3.2.25 on 2026-10-04 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0235_auto_20230316_2023'),
        ('pretix_attendance_certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecertificatelayout',
            name='active_events',
            field=models.ManyToManyField(related_name='active_organizer_certificate_layouts', to='pretixbase.Event'),
        ),
        migrations.AddField(
            model_name='attendancecertificatelayout',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_certificate_layouts', to='pretixbase.organizer'),
        ),
        migrations.AlterField(
            model_name='attendancecertificatelayout',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_certificate_layouts', to='pretixbase.event'),
        ),
        migrations.AddConstraint(
            model_name='attendancecertificatelayout',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('event__isnull', False), ('organizer__isnull', True)), models.Q(('event__isnull', True), ('organizer__isnull', False)), _connector='OR'), name='attendance_certificate_layout_event_xor_organizer'),
        ),
    ]
