# Generated by Django 3.2.25 on 2026-10-04 12:46

from django.db import migrations
import i18nfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_attendance_certificate', '0002_organizer_wide_layouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecertificatelayout',
            name='mail_subject',
            field=i18nfield.fields.I18nCharField(default='[{event}] Your certificate of attendance', max_length=255),
        ),
        migrations.AddField(
            model_name='attendancecertificatelayout',
            name='mail_text',
            field=i18nfield.fields.I18nTextField(default='Hello,\n\nplease find your certificate of attendance for {event} attached to this email.\n\nBest regards'),
        ),
    ]
